// <auto-generated />
namespace TrimAplikacija_V2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class company_add_index_to_name_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company_add_index_to_name_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202105231931456_company_add_index_to_name_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
