// <auto-generated />
namespace TrimAplikacija_V2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class set_company_fk_to_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_company_fk_to_required));
        
        string IMigrationMetadata.Id
        {
            get { return "202105231519330_set_company_fk_to_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
