// <auto-generated />
namespace TrimAplikacija_V2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_payment_date_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_payment_date_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202105281915357_update_payment_date_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
